# Generated by Django 5.2.16 on 2026-08-01 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อรอบ')),
                ('times_per_month', models.PositiveSmallIntegerField(choices=[(1, 'เดือนละ 1 ครั้ง'), (2, 'เดือนละ 2 ครั้ง')], default=1, verbose_name='จ่ายกี่ครั้งต่อเดือน')),
                ('pay_day_1', models.PositiveSmallIntegerField(default=30, verbose_name='วันจ่ายครั้งที่ 1')),
                ('pay_day_2', models.PositiveSmallIntegerField(blank=True, help_text='กรอกเฉพาะเมื่อจ่ายเดือนละ 2 ครั้ง', null=True, verbose_name='วันจ่ายครั้งที่ 2')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
            ],
            options={
                'verbose_name': 'รอบจ่ายเงิน',
                'verbose_name_plural': 'รอบจ่ายเงิน',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='เลขที่บิล')),
                ('po_no', models.CharField(blank=True, db_index=True, help_text='ได้มาหลังชำระเงินผ่านระบบบริษัท', max_length=30, verbose_name='เลข PO')),
                ('period_start', models.DateField(verbose_name='รอบวันที่')),
                ('period_end', models.DateField(verbose_name='ถึงวันที่')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดรวม (บาท)')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('issued', 'ออกบิลแล้ว'), ('paid', 'จ่ายแล้ว'), ('cancelled', 'ยกเลิก')], db_index=True, default='draft', max_length=10, verbose_name='สถานะ')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='ออกบิลเมื่อ')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='จ่ายเมื่อ')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_issued', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ออกบิล')),
                ('truck_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='fleet.truckowner', verbose_name='เจ้าของรถ')),
            ],
            options={
                'verbose_name': 'ใบวางบิล',
                'verbose_name_plural': 'ใบวางบิล',
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน (บาท)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill', verbose_name='ใบวางบิล')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill_item', to='jobs.booking', verbose_name='งาน')),
            ],
            options={
                'verbose_name': 'รายการในบิล',
                'verbose_name_plural': 'รายการในบิล',
                'ordering': ['booking__appointment_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อเกณฑ์')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ค่าบริการพื้นฐาน (บาท)')),
                ('included_km', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='ระยะทางที่รวมในราคาพื้นฐาน (กม.)')),
                ('price_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ค่าเดินทางส่วนเกิน (บาท/กม.)')),
                ('effective_from', models.DateField(db_index=True, verbose_name='เริ่มใช้วันที่')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_rates', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ตั้งค่า')),
            ],
            options={
                'verbose_name': 'เกณฑ์ราคา',
                'verbose_name_plural': 'เกณฑ์ราคา',
                'ordering': ['-effective_from'],
            },
        ),
    ]
