# Generated by Django 5.2.16 on 2026-08-01 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อผู้ประกอบการ')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทร')),
                ('tax_id', models.CharField(blank=True, max_length=13, verbose_name='เลขประจำตัวผู้เสียภาษี')),
                ('bank_account', models.CharField(blank=True, max_length=30, verbose_name='เลขบัญชีธนาคาร')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='ธนาคาร')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='truck_owner', to=settings.AUTH_USER_MODEL, verbose_name='บัญชีผู้ใช้')),
            ],
            options={
                'verbose_name': 'เจ้าของรถสไลด์',
                'verbose_name_plural': 'เจ้าของรถสไลด์',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ทะเบียนรถ')),
                ('type', models.CharField(choices=[('slide', 'รถสไลด์'), ('lift', 'รถยก')], default='slide', max_length=10, verbose_name='ประเภท')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='ยี่ห้อ')),
                ('capacity_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='น้ำหนักบรรทุก (กก.)')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='ประกันหมดอายุ')),
                ('tax_expiry', models.DateField(blank=True, null=True, verbose_name='ภาษีหมดอายุ')),
                ('is_active', models.BooleanField(default=True, verbose_name='พร้อมใช้งาน')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='fleet.truckowner', verbose_name='เจ้าของ')),
            ],
            options={
                'verbose_name': 'รถ',
                'verbose_name_plural': 'รถ',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='ชื่อ-นามสกุล')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทร')),
                ('national_id', models.CharField(blank=True, max_length=13, verbose_name='เลขบัตรประชาชน')),
                ('license_no', models.CharField(blank=True, max_length=30, verbose_name='เลขใบขับขี่')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='ใบขับขี่หมดอายุ')),
                ('photo', models.ImageField(blank=True, upload_to='drivers/', verbose_name='รูปโปรไฟล์')),
                ('is_backup', models.BooleanField(default=False, help_text='คนขับหลักไม่ต้องติ๊ก', verbose_name='เป็นคนขับเสริม')),
                ('is_available', models.BooleanField(default=True, verbose_name='สถานะว่าง')),
                ('approval_status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติ'), ('rejected', 'ไม่อนุมัติ')], default='pending', max_length=10, verbose_name='สถานะอนุมัติ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เพิ่มเมื่อ')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='fleet.truck', verbose_name='รถที่รับผิดชอบ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='fleet.truckowner', verbose_name='สังกัดเจ้าของรถ')),
            ],
            options={
                'verbose_name': 'คนขับ',
                'verbose_name_plural': 'คนขับ',
                'ordering': ['owner', '-is_available', 'name'],
                'indexes': [models.Index(fields=['owner', 'is_available'], name='fleet_drive_owner_i_5804e2_idx')],
            },
        ),
    ]
