# Generated by Django 5.2.16 on 2026-08-01 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='รหัสลูกค้า')),
                ('type', models.CharField(choices=[('person', 'บุคคลธรรมดา'), ('company', 'นิติบุคคล')], default='person', max_length=10, verbose_name='ประเภท')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='ชื่อลูกค้า / ชื่อบริษัท')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='เบอร์โทร')),
                ('phone_alt', models.CharField(blank=True, max_length=20, verbose_name='เบอร์สำรอง')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('tax_id', models.CharField(blank=True, max_length=13, verbose_name='เลขประจำตัวผู้เสียภาษี')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
            ],
            options={
                'verbose_name': 'ลูกค้า',
                'verbose_name_plural': 'ลูกค้า',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='ยี่ห้อ')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='รุ่น')),
                ('plate', models.CharField(db_index=True, max_length=20, verbose_name='ทะเบียน')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='สี')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'รถของลูกค้า',
                'verbose_name_plural': 'รถของลูกค้า',
                'ordering': ['plate'],
            },
        ),
    ]
