# Generated by Django 5.2.16 on 2026-08-01 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='เลขที่ใบจอง')),
                ('appointment_at', models.DateTimeField(db_index=True, verbose_name='วันเวลานัดหมาย')),
                ('pickup_address', models.TextField(verbose_name='จุดรับรถ')),
                ('dropoff_address', models.TextField(verbose_name='จุดส่งรถ')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='ระยะทาง (กม.)')),
                ('note', models.TextField(blank=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='รับงานเมื่อ')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าบริการ (บาท)')),
                ('extra_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าใช้จ่ายเพิ่มเติม')),
                ('status', models.CharField(choices=[('pending_accept', 'รอรับงาน'), ('accepted', 'รับงานแล้ว'), ('pending_approval', 'รออนุมัติ'), ('shr_approved', 'ผจก.อนุมัติ'), ('accounting_review', 'งานบัญชีตรวจสอบ'), ('approved', 'อนุมัติใบจอง'), ('in_progress', 'กำลังดำเนินงาน'), ('closed', 'ปิดงาน'), ('cancelled', 'ยกเลิก')], db_index=True, default='pending_accept', max_length=20, verbose_name='สถานะ')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='ปิดงานเมื่อ')),
                ('cancelled_reason', models.CharField(blank=True, max_length=300, verbose_name='เหตุผลที่ยกเลิก')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_created', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้างใบจอง')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer', verbose_name='ลูกค้า')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='fleet.driver', verbose_name='คนขับ')),
                ('sales', models.ForeignKey(blank=True, help_text='ระบุแล้วเซลล์คนนี้จะเห็นใบจองนี้ในระบบของตัวเอง', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_as_sales', to=settings.AUTH_USER_MODEL, verbose_name='เซลล์ผู้ดูแล')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='fleet.truck', verbose_name='รถที่ใช้')),
                ('truck_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='fleet.truckowner', verbose_name='เจ้าของรถผู้รับงาน')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customervehicle', verbose_name='รถที่ขนย้าย')),
            ],
            options={
                'verbose_name': 'ใบจองคิว',
                'verbose_name_plural': 'ใบจองคิว',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('pending_accept', 'รอรับงาน'), ('accepted', 'รับงานแล้ว'), ('pending_approval', 'รออนุมัติ'), ('shr_approved', 'ผจก.อนุมัติ'), ('accounting_review', 'งานบัญชีตรวจสอบ'), ('approved', 'อนุมัติใบจอง'), ('in_progress', 'กำลังดำเนินงาน'), ('closed', 'ปิดงาน'), ('cancelled', 'ยกเลิก')], max_length=20, verbose_name='จากสถานะ')),
                ('to_status', models.CharField(choices=[('pending_accept', 'รอรับงาน'), ('accepted', 'รับงานแล้ว'), ('pending_approval', 'รออนุมัติ'), ('shr_approved', 'ผจก.อนุมัติ'), ('accounting_review', 'งานบัญชีตรวจสอบ'), ('approved', 'อนุมัติใบจอง'), ('in_progress', 'กำลังดำเนินงาน'), ('closed', 'ปิดงาน'), ('cancelled', 'ยกเลิก')], max_length=20, verbose_name='เป็นสถานะ')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เมื่อ')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='jobs.booking', verbose_name='ใบจอง')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_actions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ดำเนินการ')),
            ],
            options={
                'verbose_name': 'ประวัติสถานะใบจอง',
                'verbose_name_plural': 'ประวัติสถานะใบจอง',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('photo_before', 'ถ่ายภาพรถก่อนขึ้นรถสไลด์'), ('photo_loaded', 'ถ่ายภาพหลังขึ้นรถสไลด์แล้ว'), ('on_the_way', 'กำลังเดินทาง (แผนที่)'), ('delivered', 'ส่งมอบรถ + ถ่ายภาพหลังลงจากรถสไลด์'), ('finished', 'ปิดงาน')], max_length=20, verbose_name='ขั้นตอน')),
                ('is_done', models.BooleanField(default=False, verbose_name='ทำแล้ว')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='ทำเมื่อ')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ละติจูด')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ลองจิจูด')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='หมายเหตุ')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='jobs.booking', verbose_name='ใบจอง')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_steps_done', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ทำ')),
            ],
            options={
                'verbose_name': 'ขั้นตอนการดำเนินงาน',
                'verbose_name_plural': 'ขั้นตอนการดำเนินงาน',
                'ordering': ['booking', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jobs/%Y/%m/', verbose_name='รูปภาพ')),
                ('angle', models.CharField(blank=True, help_text='เช่น หน้า หลัง ซ้าย ขวา', max_length=50, verbose_name='มุมภาพ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='อัปโหลดเมื่อ')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='jobs.jobstep', verbose_name='ขั้นตอน')),
            ],
            options={
                'verbose_name': 'รูปถ่ายงาน',
                'verbose_name_plural': 'รูปถ่ายงาน',
                'ordering': ['step', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-appointment_at'], name='jobs_bookin_status_290f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['truck_owner', 'status'], name='jobs_bookin_truck_o_c081b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobstep',
            constraint=models.UniqueConstraint(fields=('booking', 'code'), name='uniq_step_per_booking'),
        ),
    ]
