# Generated by Django 5.2.16 on 2026-08-02 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('edit', 'ขอแก้ไข'), ('cancel', 'ขอยกเลิก')], max_length=10, verbose_name='ประเภทคำขอ')),
                ('reason', models.TextField(verbose_name='เหตุผล')),
                ('status', models.CharField(choices=[('pending', 'รอผู้จัดการพิจารณา'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ไม่อนุมัติ'), ('done', 'แก้ไขเรียบร้อยแล้ว')], db_index=True, default='pending', max_length=10, verbose_name='สถานะคำขอ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ขอเมื่อ')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='พิจารณาเมื่อ')),
                ('decision_note', models.CharField(blank=True, max_length=300, verbose_name='หมายเหตุผู้พิจารณา')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='jobs.booking', verbose_name='ใบจอง')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขอ')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests_decided', to=settings.AUTH_USER_MODEL, verbose_name='ผู้พิจารณา')),
            ],
            options={
                'verbose_name': 'คำขอแก้ไข/ยกเลิก',
                'verbose_name_plural': 'คำขอแก้ไข/ยกเลิก',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='jobs_bookin_status_aeabfa_idx')],
            },
        ),
    ]
