# Generated by Django 5.2.16 on 2026-08-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='รูปโปรไฟล์'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_verified',
            field=models.BooleanField(default=False, help_text='แอดมินติ๊กหลังตรวจเอกสารยืนยันตัวตน', verbose_name='ยืนยันตัวตนแล้ว'),
        ),
    ]
