# Generated by Django 5.2.16 on 2026-08-03 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_id_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_role', models.CharField(choices=[('requester', 'ผู้จองคิว'), ('sales', 'เซลล์'), ('trailer', 'เจ้าของรถสไลด์'), ('shr', 'ผู้จัดการสาขา'), ('accounting', 'งานบัญชี'), ('executive', 'ผู้บริหาร'), ('admin', 'แอดมิน')], max_length=20, verbose_name='จากตำแหน่ง')),
                ('to_role', models.CharField(choices=[('requester', 'ผู้จองคิว'), ('sales', 'เซลล์'), ('trailer', 'เจ้าของรถสไลด์'), ('shr', 'ผู้จัดการสาขา'), ('accounting', 'งานบัญชี'), ('executive', 'ผู้บริหาร'), ('admin', 'แอดมิน')], max_length=20, verbose_name='เป็นตำแหน่ง')),
                ('status', models.CharField(choices=[('pending', 'รอเจ้าของบัญชียืนยัน'), ('accepted', 'ยอมรับแล้ว'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก')], db_index=True, default='pending', max_length=10, verbose_name='สถานะ')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='เหตุผลจากแอดมิน')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ขอเมื่อ')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='ตัดสินเมื่อ')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_changes_requested', to=settings.AUTH_USER_MODEL, verbose_name='แอดมินผู้ขอ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_changes', to=settings.AUTH_USER_MODEL, verbose_name='เจ้าของบัญชี')),
            ],
            options={
                'verbose_name': 'คำขอเปลี่ยนสิทธิ์',
                'verbose_name_plural': 'คำขอเปลี่ยนสิทธิ์',
                'ordering': ['-created_at'],
            },
        ),
    ]
