# Generated by Django 5.2.16 on 2026-08-01 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อเอกสาร')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='คำอธิบาย')),
                ('file', models.FileField(upload_to='docs/%Y/%m/', verbose_name='ไฟล์')),
                ('visible_roles', models.JSONField(default=list, help_text='ว่างไว้ = ทุกตำแหน่งเห็น', verbose_name='ตำแหน่งที่มองเห็น')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='อัปโหลดเมื่อ')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docs_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อัปโหลด')),
            ],
            options={
                'verbose_name': 'เอกสารการใช้งานระบบ',
                'verbose_name_plural': 'เอกสารการใช้งานระบบ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('job', 'งาน'), ('approval', 'การอนุมัติ'), ('permission', 'สิทธิ์การเข้าถึง'), ('system', 'ระบบ')], default='system', max_length=20, verbose_name='ประเภท')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('body', models.CharField(blank=True, max_length=500, verbose_name='รายละเอียด')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='ลิงก์ปลายทาง')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='อ่านแล้ว')),
                ('need_ack', models.BooleanField(default=False, verbose_name='ต้องกดยืนยัน')),
                ('acked_at', models.DateTimeField(blank=True, null=True, verbose_name='ยืนยันเมื่อ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='เมื่อ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับ')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือน',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx')],
            },
        ),
    ]
