# Generated by Django 5.2.16 on 2026-08-03 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='เริ่มเมื่อ')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ออกเมื่อ')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impersonations_made', to=settings.AUTH_USER_MODEL, verbose_name='แอดมิน')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impersonations_received', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้ที่ถูกสวมสิทธิ์')),
            ],
            options={
                'verbose_name': 'ประวัติการสวมสิทธิ์',
                'verbose_name_plural': 'ประวัติการสวมสิทธิ์',
                'ordering': ['-started_at'],
            },
        ),
    ]
